### ISSUE TITLE
Good Initiative - Do you need help 

### ISSUE THREAD

**Issue by lironsher** [CoericK/react-native-account-kit#2]
Hi
I'm also working on react native app.
Do you want to work on this bridge together?

**Comment by CoericK** [comment]
Hey @lironsher i didnt see the issues, i just see your message, yeah sure, im releasing the android support today, there should be many improvements, maybe you can work on the iOS support? if so just send a PR and let me know.

**Comment by lironsher** [comment]
Hi
I'm working on the ios version, but there is something I don't understand
in your code :

why trim the auth code to 10 :

authorizationCode.substring(0, 10)

???

Thanks

Liron Sher
